// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/deviceId/enriched_details.proto

package deviceId

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnrichedDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrichedDetails) Reset()         { *m = EnrichedDetails{} }
func (m *EnrichedDetails) String() string { return proto.CompactTextString(m) }
func (*EnrichedDetails) ProtoMessage()    {}
func (*EnrichedDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d16f8ec54ff093, []int{0}
}

func (m *EnrichedDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrichedDetails.Unmarshal(m, b)
}
func (m *EnrichedDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrichedDetails.Marshal(b, m, deterministic)
}
func (m *EnrichedDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrichedDetails.Merge(m, src)
}
func (m *EnrichedDetails) XXX_Size() int {
	return xxx_messageInfo_EnrichedDetails.Size(m)
}
func (m *EnrichedDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrichedDetails.DiscardUnknown(m)
}

var xxx_messageInfo_EnrichedDetails proto.InternalMessageInfo

func (m *EnrichedDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnrichedDetails) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *EnrichedDetails) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func init() {
	proto.RegisterType((*EnrichedDetails)(nil), "kafmesh.deviceId.EnrichedDetails")
}

func init() {
	proto.RegisterFile("kafmesh/deviceId/enriched_details.proto", fileDescriptor_34d16f8ec54ff093)
}

var fileDescriptor_34d16f8ec54ff093 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcf, 0x4e, 0x4c, 0xcb,
	0x4d, 0x2d, 0xce, 0xd0, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xf5, 0x4c, 0xd1, 0x4f, 0xcd, 0x2b,
	0xca, 0x4c, 0xce, 0x48, 0x4d, 0x89, 0x4f, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0x29, 0xd6, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x2a, 0xd4, 0x83, 0x29, 0x54, 0xca, 0xe6, 0xe2, 0x77, 0x85,
	0xaa, 0x75, 0x81, 0x28, 0x15, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xe4, 0xb9, 0xb8, 0x93, 0x4b, 0x8b, 0x4b, 0xf2, 0x73, 0x53,
	0x8b, 0xe2, 0x33, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0xb8, 0x60, 0x42, 0x9e, 0x29,
	0x42, 0xca, 0x5c, 0xbc, 0x70, 0x05, 0x60, 0xdd, 0xcc, 0x60, 0xdd, 0x3c, 0x30, 0x41, 0xbf, 0xc4,
	0xdc, 0x54, 0x27, 0xae, 0x28, 0x0e, 0x98, 0xc5, 0x49, 0x6c, 0x60, 0x17, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x6e, 0x7a, 0xb0, 0x39, 0xbc, 0x00, 0x00, 0x00,
}
