// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: kafmesh/deviceId/heartbeat.proto

package deviceId

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	IsHealthy bool                 `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_deviceId_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_deviceId_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_kafmesh_deviceId_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Heartbeat) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

var File_kafmesh_deviceId_heartbeat_proto protoreflect.FileDescriptor

var file_kafmesh_deviceId_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x79, 0x42, 0x0a, 0x5a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kafmesh_deviceId_heartbeat_proto_rawDescOnce sync.Once
	file_kafmesh_deviceId_heartbeat_proto_rawDescData = file_kafmesh_deviceId_heartbeat_proto_rawDesc
)

func file_kafmesh_deviceId_heartbeat_proto_rawDescGZIP() []byte {
	file_kafmesh_deviceId_heartbeat_proto_rawDescOnce.Do(func() {
		file_kafmesh_deviceId_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafmesh_deviceId_heartbeat_proto_rawDescData)
	})
	return file_kafmesh_deviceId_heartbeat_proto_rawDescData
}

var file_kafmesh_deviceId_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kafmesh_deviceId_heartbeat_proto_goTypes = []interface{}{
	(*Heartbeat)(nil),           // 0: kafmesh.deviceId.Heartbeat
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kafmesh_deviceId_heartbeat_proto_depIdxs = []int32{
	1, // 0: kafmesh.deviceId.Heartbeat.time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kafmesh_deviceId_heartbeat_proto_init() }
func file_kafmesh_deviceId_heartbeat_proto_init() {
	if File_kafmesh_deviceId_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafmesh_deviceId_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafmesh_deviceId_heartbeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafmesh_deviceId_heartbeat_proto_goTypes,
		DependencyIndexes: file_kafmesh_deviceId_heartbeat_proto_depIdxs,
		MessageInfos:      file_kafmesh_deviceId_heartbeat_proto_msgTypes,
	}.Build()
	File_kafmesh_deviceId_heartbeat_proto = out.File
	file_kafmesh_deviceId_heartbeat_proto_rawDesc = nil
	file_kafmesh_deviceId_heartbeat_proto_goTypes = nil
	file_kafmesh_deviceId_heartbeat_proto_depIdxs = nil
}
