name: assignments
description: The assignments component keeps the device to customer assignments up to date.

sources:
  - message: deviceId.customer
  - message: customerId.details
    compact: true

views:
  - message: deviceId.customer
  - message: customerId.details
