name: details
description: The details component handles the flow for device details.

sources:
  - message: deviceId.details

processors:
  - name: enricher
    description: Provides enriched device details with customer information.
    inputs:
      - message: deviceId.details
      - message: deviceId.customer
    lookups:
      - message: customerId.details
        type: protobuf
    outputs:
      - message: deviceId.enrichedDetails
        description: Enriched device details
    persistence:
      message: deviceId.enrichedDetailsState

sinks:
  - message: deviceId.enrichedDetails
    name: Enriched Detail Warehouse Sink
    description: Sinks enriched device details to the warehouse database.

views:
  - message: deviceId.enrichedDetails
