name: details
description: The details component handles the flow for device details.

sources:
  - message: deviceId.details
    type: protobuf
    partitions: 10

processors:
  - name: enricher
    description: Provides enriched device details with customer information.
    inputs:
      - message: deviceId.details
        type: protobuf
      - message: deviceId.customer
        type: protobuf
    lookups:
      - message: customerId.details
        type: protobuf
    outputs:
      - message: deviceId.enrichedDetails
        description: Enriched device details
        type: protobuf
        partitions: 10
    persistence:
      message: deviceId.enrichedDetailsState
      type: protobuf

sinks:
  - message: deviceId.enrichedDetails
    name: Enriched Detail Warehouse Sink
    description: Sinks enriched device details to the warehouse database.
    type: protobuf

views:
  - message: deviceId.enrichedDetails
