// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/history/v1/history_api.proto

package historyv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{0}
}

func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (m *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(m, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

type LastDetailsRequest struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastDetailsRequest) Reset()         { *m = LastDetailsRequest{} }
func (m *LastDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*LastDetailsRequest) ProtoMessage()    {}
func (*LastDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{1}
}

func (m *LastDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastDetailsRequest.Unmarshal(m, b)
}
func (m *LastDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastDetailsRequest.Marshal(b, m, deterministic)
}
func (m *LastDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastDetailsRequest.Merge(m, src)
}
func (m *LastDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_LastDetailsRequest.Size(m)
}
func (m *LastDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastDetailsRequest proto.InternalMessageInfo

func (m *LastDetailsRequest) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type Details struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CustomerId           int64                `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName         string               `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{2}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Details) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Details) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Details) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

type LastDetailsResponse struct {
	// Types that are valid to be assigned to Response:
	//	*LastDetailsResponse_ResponseNone
	//	*LastDetailsResponse_ResponseDetails
	Response             isLastDetailsResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *LastDetailsResponse) Reset()         { *m = LastDetailsResponse{} }
func (m *LastDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*LastDetailsResponse) ProtoMessage()    {}
func (*LastDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{3}
}

func (m *LastDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastDetailsResponse.Unmarshal(m, b)
}
func (m *LastDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastDetailsResponse.Marshal(b, m, deterministic)
}
func (m *LastDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastDetailsResponse.Merge(m, src)
}
func (m *LastDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_LastDetailsResponse.Size(m)
}
func (m *LastDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastDetailsResponse proto.InternalMessageInfo

type isLastDetailsResponse_Response interface {
	isLastDetailsResponse_Response()
}

type LastDetailsResponse_ResponseNone struct {
	ResponseNone *None `protobuf:"bytes,1,opt,name=response_none,json=responseNone,proto3,oneof"`
}

type LastDetailsResponse_ResponseDetails struct {
	ResponseDetails *Details `protobuf:"bytes,2,opt,name=response_details,json=responseDetails,proto3,oneof"`
}

func (*LastDetailsResponse_ResponseNone) isLastDetailsResponse_Response() {}

func (*LastDetailsResponse_ResponseDetails) isLastDetailsResponse_Response() {}

func (m *LastDetailsResponse) GetResponse() isLastDetailsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *LastDetailsResponse) GetResponseNone() *None {
	if x, ok := m.GetResponse().(*LastDetailsResponse_ResponseNone); ok {
		return x.ResponseNone
	}
	return nil
}

func (m *LastDetailsResponse) GetResponseDetails() *Details {
	if x, ok := m.GetResponse().(*LastDetailsResponse_ResponseDetails); ok {
		return x.ResponseDetails
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LastDetailsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LastDetailsResponse_ResponseNone)(nil),
		(*LastDetailsResponse_ResponseDetails)(nil),
	}
}

type LastHeartbeatRequest struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastHeartbeatRequest) Reset()         { *m = LastHeartbeatRequest{} }
func (m *LastHeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*LastHeartbeatRequest) ProtoMessage()    {}
func (*LastHeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{4}
}

func (m *LastHeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastHeartbeatRequest.Unmarshal(m, b)
}
func (m *LastHeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastHeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *LastHeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastHeartbeatRequest.Merge(m, src)
}
func (m *LastHeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_LastHeartbeatRequest.Size(m)
}
func (m *LastHeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastHeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastHeartbeatRequest proto.InternalMessageInfo

func (m *LastHeartbeatRequest) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type Heartbeat struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	IsHealthy            bool                 `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	CustomerId           int64                `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName         string               `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{5}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Heartbeat) GetIsHealthy() bool {
	if m != nil {
		return m.IsHealthy
	}
	return false
}

func (m *Heartbeat) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Heartbeat) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

type LastHeartbeatResponse struct {
	// Types that are valid to be assigned to Response:
	//	*LastHeartbeatResponse_ResponseNone
	//	*LastHeartbeatResponse_ResponseHeartbeat
	Response             isLastHeartbeatResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *LastHeartbeatResponse) Reset()         { *m = LastHeartbeatResponse{} }
func (m *LastHeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*LastHeartbeatResponse) ProtoMessage()    {}
func (*LastHeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7675dbb145e08baa, []int{6}
}

func (m *LastHeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastHeartbeatResponse.Unmarshal(m, b)
}
func (m *LastHeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastHeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *LastHeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastHeartbeatResponse.Merge(m, src)
}
func (m *LastHeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_LastHeartbeatResponse.Size(m)
}
func (m *LastHeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastHeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastHeartbeatResponse proto.InternalMessageInfo

type isLastHeartbeatResponse_Response interface {
	isLastHeartbeatResponse_Response()
}

type LastHeartbeatResponse_ResponseNone struct {
	ResponseNone *None `protobuf:"bytes,1,opt,name=response_none,json=responseNone,proto3,oneof"`
}

type LastHeartbeatResponse_ResponseHeartbeat struct {
	ResponseHeartbeat *Heartbeat `protobuf:"bytes,2,opt,name=response_heartbeat,json=responseHeartbeat,proto3,oneof"`
}

func (*LastHeartbeatResponse_ResponseNone) isLastHeartbeatResponse_Response() {}

func (*LastHeartbeatResponse_ResponseHeartbeat) isLastHeartbeatResponse_Response() {}

func (m *LastHeartbeatResponse) GetResponse() isLastHeartbeatResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *LastHeartbeatResponse) GetResponseNone() *None {
	if x, ok := m.GetResponse().(*LastHeartbeatResponse_ResponseNone); ok {
		return x.ResponseNone
	}
	return nil
}

func (m *LastHeartbeatResponse) GetResponseHeartbeat() *Heartbeat {
	if x, ok := m.GetResponse().(*LastHeartbeatResponse_ResponseHeartbeat); ok {
		return x.ResponseHeartbeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LastHeartbeatResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LastHeartbeatResponse_ResponseNone)(nil),
		(*LastHeartbeatResponse_ResponseHeartbeat)(nil),
	}
}

func init() {
	proto.RegisterType((*None)(nil), "kafmesh.history.v1.None")
	proto.RegisterType((*LastDetailsRequest)(nil), "kafmesh.history.v1.LastDetailsRequest")
	proto.RegisterType((*Details)(nil), "kafmesh.history.v1.Details")
	proto.RegisterType((*LastDetailsResponse)(nil), "kafmesh.history.v1.LastDetailsResponse")
	proto.RegisterType((*LastHeartbeatRequest)(nil), "kafmesh.history.v1.LastHeartbeatRequest")
	proto.RegisterType((*Heartbeat)(nil), "kafmesh.history.v1.Heartbeat")
	proto.RegisterType((*LastHeartbeatResponse)(nil), "kafmesh.history.v1.LastHeartbeatResponse")
}

func init() {
	proto.RegisterFile("kafmesh/history/v1/history_api.proto", fileDescriptor_7675dbb145e08baa)
}

var fileDescriptor_7675dbb145e08baa = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xce, 0xb6, 0xa1, 0x66, 0x4f, 0x1a, 0xd4, 0xa3, 0x42, 0x48, 0x29, 0x0d, 0xab, 0x68, 0xbc,
	0x99, 0xb0, 0xe9, 0x03, 0x88, 0xc5, 0x8b, 0x0d, 0x4a, 0x90, 0x41, 0xbc, 0xf0, 0xc2, 0x30, 0xe9,
	0x9e, 0x76, 0x07, 0xb3, 0x3b, 0x71, 0x67, 0x12, 0xe8, 0x73, 0xf8, 0x02, 0x5e, 0x8b, 0x97, 0x3e,
	0x89, 0x4f, 0x24, 0x3b, 0x3b, 0xb3, 0xf4, 0x27, 0x62, 0x85, 0xde, 0x4d, 0xbe, 0x7c, 0x3f, 0xe7,
	0x6f, 0xe1, 0xd9, 0x17, 0x71, 0x96, 0x93, 0xce, 0xc6, 0x99, 0xd4, 0x46, 0x95, 0x17, 0xe3, 0x4d,
	0xec, 0x9f, 0x73, 0xb1, 0x92, 0x6c, 0x55, 0x2a, 0xa3, 0x10, 0x1d, 0x8b, 0xb9, 0xbf, 0xd8, 0x26,
	0x1e, 0x1c, 0x9d, 0x2b, 0x75, 0xbe, 0xa4, 0xb1, 0x65, 0x2c, 0xd6, 0x67, 0x63, 0x23, 0x73, 0xd2,
	0x46, 0xe4, 0xab, 0x5a, 0x14, 0xed, 0x41, 0x7b, 0xa6, 0x0a, 0x8a, 0x62, 0xc0, 0x77, 0x42, 0x9b,
	0x37, 0x64, 0x84, 0x5c, 0x6a, 0x4e, 0x5f, 0xd7, 0xa4, 0x0d, 0x1e, 0x40, 0x98, 0xd2, 0x46, 0x9e,
	0xd2, 0x5c, 0xa6, 0xfd, 0x60, 0x18, 0x8c, 0x76, 0x79, 0xa7, 0x06, 0xa6, 0x69, 0xf4, 0x2d, 0x80,
	0x7b, 0x8e, 0x8f, 0x0c, 0xda, 0x95, 0xb3, 0xe5, 0x74, 0x27, 0x03, 0x56, 0xc7, 0x32, 0x1f, 0xcb,
	0x3e, 0xf8, 0x58, 0x6e, 0x79, 0x88, 0xd0, 0x2e, 0x44, 0x4e, 0xfd, 0x9d, 0x61, 0x30, 0x0a, 0xb9,
	0x7d, 0xe3, 0x11, 0x74, 0x4f, 0xd7, 0xda, 0xa8, 0x9c, 0xca, 0x2a, 0x6e, 0xd7, 0xc6, 0x81, 0x87,
	0xa6, 0x29, 0x3e, 0x85, 0x5e, 0x43, 0xb0, 0xea, 0xb6, 0x55, 0xef, 0x7b, 0x70, 0x26, 0x72, 0x8a,
	0x7e, 0x06, 0xf0, 0xe8, 0x4a, 0x27, 0x7a, 0xa5, 0x0a, 0x4d, 0xf8, 0x0a, 0x7a, 0xa5, 0x7b, 0xcf,
	0x0b, 0x55, 0xf8, 0x52, 0xfb, 0xec, 0xe6, 0xd4, 0x58, 0x35, 0x91, 0xa4, 0xc5, 0xf7, 0xbd, 0xa0,
	0xfa, 0x8d, 0x09, 0x3c, 0x68, 0x0c, 0xd2, 0xda, 0xdc, 0x96, 0xdf, 0x9d, 0x1c, 0x6c, 0xf3, 0x70,
	0xf9, 0x49, 0x8b, 0xdf, 0xf7, 0x32, 0x07, 0x9d, 0x00, 0x74, 0x3c, 0x14, 0x1d, 0xc3, 0xe3, 0xaa,
	0xda, 0x84, 0x44, 0x69, 0x16, 0x24, 0xcc, 0xad, 0x26, 0xff, 0x3d, 0x80, 0xb0, 0x51, 0xfc, 0xf7,
	0xec, 0x0f, 0x01, 0xa4, 0x9e, 0x67, 0x24, 0x96, 0x26, 0xbb, 0xb0, 0x2d, 0x74, 0x78, 0x28, 0x75,
	0x52, 0x03, 0x77, 0xb4, 0x86, 0x5f, 0x01, 0x3c, 0xb9, 0xd6, 0xd8, 0x5d, 0x2d, 0x62, 0x06, 0xd8,
	0x18, 0x64, 0xde, 0xde, 0xad, 0xe2, 0x70, 0x9b, 0x4b, 0x53, 0x43, 0xd2, 0xe2, 0x0f, 0xbd, 0xb4,
	0x01, 0x2f, 0xaf, 0x63, 0xf2, 0x3b, 0x00, 0x48, 0x6a, 0xe5, 0xeb, 0xf7, 0x53, 0xfc, 0x0c, 0xdd,
	0x4b, 0xb7, 0x84, 0xcf, 0xb7, 0xb9, 0xdf, 0xfc, 0x6c, 0x06, 0x2f, 0xfe, 0xc9, 0x73, 0xb3, 0x48,
	0xa1, 0x77, 0x65, 0x48, 0x38, 0xfa, 0x9b, 0xf2, 0xfa, 0x81, 0x0c, 0x5e, 0xde, 0x82, 0x59, 0xa7,
	0x9c, 0x0c, 0x3f, 0x85, 0x8e, 0xb3, 0x89, 0x7f, 0xec, 0xe0, 0x5b, 0xa7, 0x73, 0x7d, 0xb2, 0x8f,
	0xf1, 0x62, 0xcf, 0x1e, 0xcb, 0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xef, 0x14, 0x01,
	0x69, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HistoryAPIClient is the client API for HistoryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HistoryAPIClient interface {
	LastDetails(ctx context.Context, in *LastDetailsRequest, opts ...grpc.CallOption) (*LastDetailsResponse, error)
	LastHeartbeat(ctx context.Context, in *LastHeartbeatRequest, opts ...grpc.CallOption) (*LastHeartbeatResponse, error)
}

type historyAPIClient struct {
	cc *grpc.ClientConn
}

func NewHistoryAPIClient(cc *grpc.ClientConn) HistoryAPIClient {
	return &historyAPIClient{cc}
}

func (c *historyAPIClient) LastDetails(ctx context.Context, in *LastDetailsRequest, opts ...grpc.CallOption) (*LastDetailsResponse, error) {
	out := new(LastDetailsResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.history.v1.HistoryAPI/LastDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyAPIClient) LastHeartbeat(ctx context.Context, in *LastHeartbeatRequest, opts ...grpc.CallOption) (*LastHeartbeatResponse, error) {
	out := new(LastHeartbeatResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.history.v1.HistoryAPI/LastHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryAPIServer is the server API for HistoryAPI service.
type HistoryAPIServer interface {
	LastDetails(context.Context, *LastDetailsRequest) (*LastDetailsResponse, error)
	LastHeartbeat(context.Context, *LastHeartbeatRequest) (*LastHeartbeatResponse, error)
}

// UnimplementedHistoryAPIServer can be embedded to have forward compatible implementations.
type UnimplementedHistoryAPIServer struct {
}

func (*UnimplementedHistoryAPIServer) LastDetails(ctx context.Context, req *LastDetailsRequest) (*LastDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastDetails not implemented")
}
func (*UnimplementedHistoryAPIServer) LastHeartbeat(ctx context.Context, req *LastHeartbeatRequest) (*LastHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastHeartbeat not implemented")
}

func RegisterHistoryAPIServer(s *grpc.Server, srv HistoryAPIServer) {
	s.RegisterService(&_HistoryAPI_serviceDesc, srv)
}

func _HistoryAPI_LastDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryAPIServer).LastDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.history.v1.HistoryAPI/LastDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryAPIServer).LastDetails(ctx, req.(*LastDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryAPI_LastHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryAPIServer).LastHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.history.v1.HistoryAPI/LastHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryAPIServer).LastHeartbeat(ctx, req.(*LastHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HistoryAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kafmesh.history.v1.HistoryAPI",
	HandlerType: (*HistoryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LastDetails",
			Handler:    _HistoryAPI_LastDetails_Handler,
		},
		{
			MethodName: "LastHeartbeat",
			Handler:    _HistoryAPI_LastHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kafmesh/history/v1/history_api.proto",
}
