// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: kafmesh/api/v1/api.proto

package apiv1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetAssignmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId int64 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssignmentRequest) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type GetAssignmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId *wrappers.Int64Value `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *GetAssignmentResponse) Reset() {
	*x = GetAssignmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentResponse) ProtoMessage() {}

func (x *GetAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GetAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetAssignmentResponse) GetCustomerId() *wrappers.Int64Value {
	if x != nil {
		return x.CustomerId
	}
	return nil
}

type AssignDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId   int64 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CustomerId int64 `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *AssignDeviceRequest) Reset() {
	*x = AssignDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDeviceRequest) ProtoMessage() {}

func (x *AssignDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDeviceRequest.ProtoReflect.Descriptor instead.
func (*AssignDeviceRequest) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *AssignDeviceRequest) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *AssignDeviceRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type AssignDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignDeviceResponse) Reset() {
	*x = AssignDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDeviceResponse) ProtoMessage() {}

func (x *AssignDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDeviceResponse.ProtoReflect.Descriptor instead.
func (*AssignDeviceResponse) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{3}
}

type UpdateCustomerDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId int64  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateCustomerDetailsRequest) Reset() {
	*x = UpdateCustomerDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCustomerDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerDetailsRequest) ProtoMessage() {}

func (x *UpdateCustomerDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerDetailsRequest) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCustomerDetailsRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateCustomerDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCustomerDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCustomerDetailsResponse) Reset() {
	*x = UpdateCustomerDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCustomerDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerDetailsResponse) ProtoMessage() {}

func (x *UpdateCustomerDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerDetailsResponse) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{5}
}

type GetCustomerDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId int64 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *GetCustomerDetailsRequest) Reset() {
	*x = GetCustomerDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerDetailsRequest) ProtoMessage() {}

func (x *GetCustomerDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerDetailsRequest) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomerDetailsRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetCustomerDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *wrappers.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCustomerDetailsResponse) Reset() {
	*x = GetCustomerDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerDetailsResponse) ProtoMessage() {}

func (x *GetCustomerDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerDetailsResponse) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetCustomerDetailsResponse) GetName() *wrappers.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

type GetEgressEndpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId int64 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *GetEgressEndpointRequest) Reset() {
	*x = GetEgressEndpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEgressEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEgressEndpointRequest) ProtoMessage() {}

func (x *GetEgressEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEgressEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetEgressEndpointRequest) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetEgressEndpointRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetEgressEndpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*GetEgressEndpointResponse_ResponseNone
	//	*GetEgressEndpointResponse_ResponseUrl
	Response isGetEgressEndpointResponse_Response `protobuf_oneof:"response"`
}

func (x *GetEgressEndpointResponse) Reset() {
	*x = GetEgressEndpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEgressEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEgressEndpointResponse) ProtoMessage() {}

func (x *GetEgressEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEgressEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetEgressEndpointResponse) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{9}
}

func (m *GetEgressEndpointResponse) GetResponse() isGetEgressEndpointResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetEgressEndpointResponse) GetResponseNone() *empty.Empty {
	if x, ok := x.GetResponse().(*GetEgressEndpointResponse_ResponseNone); ok {
		return x.ResponseNone
	}
	return nil
}

func (x *GetEgressEndpointResponse) GetResponseUrl() string {
	if x, ok := x.GetResponse().(*GetEgressEndpointResponse_ResponseUrl); ok {
		return x.ResponseUrl
	}
	return ""
}

type isGetEgressEndpointResponse_Response interface {
	isGetEgressEndpointResponse_Response()
}

type GetEgressEndpointResponse_ResponseNone struct {
	ResponseNone *empty.Empty `protobuf:"bytes,1,opt,name=response_none,json=responseNone,proto3,oneof"`
}

type GetEgressEndpointResponse_ResponseUrl struct {
	ResponseUrl string `protobuf:"bytes,2,opt,name=response_url,json=responseUrl,proto3,oneof"`
}

func (*GetEgressEndpointResponse_ResponseNone) isGetEgressEndpointResponse_Response() {}

func (*GetEgressEndpointResponse_ResponseUrl) isGetEgressEndpointResponse_Response() {}

type SetEgressEndpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId int64  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Url        string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SetEgressEndpointRequest) Reset() {
	*x = SetEgressEndpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEgressEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEgressEndpointRequest) ProtoMessage() {}

func (x *SetEgressEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEgressEndpointRequest.ProtoReflect.Descriptor instead.
func (*SetEgressEndpointRequest) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *SetEgressEndpointRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SetEgressEndpointRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetEgressEndpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEgressEndpointResponse) Reset() {
	*x = SetEgressEndpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafmesh_api_v1_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEgressEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEgressEndpointResponse) ProtoMessage() {}

func (x *SetEgressEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafmesh_api_v1_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEgressEndpointResponse.ProtoReflect.Descriptor instead.
func (*SetEgressEndpointResponse) Descriptor() ([]byte, []int) {
	return file_kafmesh_api_v1_api_proto_rawDescGZIP(), []int{11}
}

var File_kafmesh_api_v1_api_proto protoreflect.FileDescriptor

var file_kafmesh_api_v1_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6b, 0x61, 0x66, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x13, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x53, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x8b, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6e, 0x6f, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00,
	0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x23,
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x55, 0x72, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x4d, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x1b,
	0x0a, 0x19, 0x53, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf5, 0x04, 0x0a, 0x03,
	0x41, 0x70, 0x69, 0x12, 0x5c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6b, 0x61, 0x66,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x59, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x23, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x74, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2c, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x29, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65,
	0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x68, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x28, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x11, 0x53, 0x65, 0x74,
	0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x28,
	0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6b, 0x61, 0x66, 0x6d, 0x65,
	0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x05, 0x61, 0x70, 0x69, 0x76, 0x31, 0xaa, 0x02, 0x0e, 0x4b,
	0x61, 0x66, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kafmesh_api_v1_api_proto_rawDescOnce sync.Once
	file_kafmesh_api_v1_api_proto_rawDescData = file_kafmesh_api_v1_api_proto_rawDesc
)

func file_kafmesh_api_v1_api_proto_rawDescGZIP() []byte {
	file_kafmesh_api_v1_api_proto_rawDescOnce.Do(func() {
		file_kafmesh_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafmesh_api_v1_api_proto_rawDescData)
	})
	return file_kafmesh_api_v1_api_proto_rawDescData
}

var file_kafmesh_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kafmesh_api_v1_api_proto_goTypes = []interface{}{
	(*GetAssignmentRequest)(nil),          // 0: kafmesh.api.v1.GetAssignmentRequest
	(*GetAssignmentResponse)(nil),         // 1: kafmesh.api.v1.GetAssignmentResponse
	(*AssignDeviceRequest)(nil),           // 2: kafmesh.api.v1.AssignDeviceRequest
	(*AssignDeviceResponse)(nil),          // 3: kafmesh.api.v1.AssignDeviceResponse
	(*UpdateCustomerDetailsRequest)(nil),  // 4: kafmesh.api.v1.UpdateCustomerDetailsRequest
	(*UpdateCustomerDetailsResponse)(nil), // 5: kafmesh.api.v1.UpdateCustomerDetailsResponse
	(*GetCustomerDetailsRequest)(nil),     // 6: kafmesh.api.v1.GetCustomerDetailsRequest
	(*GetCustomerDetailsResponse)(nil),    // 7: kafmesh.api.v1.GetCustomerDetailsResponse
	(*GetEgressEndpointRequest)(nil),      // 8: kafmesh.api.v1.GetEgressEndpointRequest
	(*GetEgressEndpointResponse)(nil),     // 9: kafmesh.api.v1.GetEgressEndpointResponse
	(*SetEgressEndpointRequest)(nil),      // 10: kafmesh.api.v1.SetEgressEndpointRequest
	(*SetEgressEndpointResponse)(nil),     // 11: kafmesh.api.v1.SetEgressEndpointResponse
	(*wrappers.Int64Value)(nil),           // 12: google.protobuf.Int64Value
	(*wrappers.StringValue)(nil),          // 13: google.protobuf.StringValue
	(*empty.Empty)(nil),                   // 14: google.protobuf.Empty
}
var file_kafmesh_api_v1_api_proto_depIdxs = []int32{
	12, // 0: kafmesh.api.v1.GetAssignmentResponse.customer_id:type_name -> google.protobuf.Int64Value
	13, // 1: kafmesh.api.v1.GetCustomerDetailsResponse.name:type_name -> google.protobuf.StringValue
	14, // 2: kafmesh.api.v1.GetEgressEndpointResponse.response_none:type_name -> google.protobuf.Empty
	0,  // 3: kafmesh.api.v1.Api.GetAssignment:input_type -> kafmesh.api.v1.GetAssignmentRequest
	2,  // 4: kafmesh.api.v1.Api.AssignDevice:input_type -> kafmesh.api.v1.AssignDeviceRequest
	4,  // 5: kafmesh.api.v1.Api.UpdateCustomerDetails:input_type -> kafmesh.api.v1.UpdateCustomerDetailsRequest
	6,  // 6: kafmesh.api.v1.Api.GetCustomerDetails:input_type -> kafmesh.api.v1.GetCustomerDetailsRequest
	8,  // 7: kafmesh.api.v1.Api.GetEgressEndpoint:input_type -> kafmesh.api.v1.GetEgressEndpointRequest
	10, // 8: kafmesh.api.v1.Api.SetEgressEndpoint:input_type -> kafmesh.api.v1.SetEgressEndpointRequest
	1,  // 9: kafmesh.api.v1.Api.GetAssignment:output_type -> kafmesh.api.v1.GetAssignmentResponse
	3,  // 10: kafmesh.api.v1.Api.AssignDevice:output_type -> kafmesh.api.v1.AssignDeviceResponse
	5,  // 11: kafmesh.api.v1.Api.UpdateCustomerDetails:output_type -> kafmesh.api.v1.UpdateCustomerDetailsResponse
	7,  // 12: kafmesh.api.v1.Api.GetCustomerDetails:output_type -> kafmesh.api.v1.GetCustomerDetailsResponse
	9,  // 13: kafmesh.api.v1.Api.GetEgressEndpoint:output_type -> kafmesh.api.v1.GetEgressEndpointResponse
	11, // 14: kafmesh.api.v1.Api.SetEgressEndpoint:output_type -> kafmesh.api.v1.SetEgressEndpointResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kafmesh_api_v1_api_proto_init() }
func file_kafmesh_api_v1_api_proto_init() {
	if File_kafmesh_api_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafmesh_api_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssignmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssignmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCustomerDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCustomerDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEgressEndpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEgressEndpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEgressEndpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafmesh_api_v1_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEgressEndpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kafmesh_api_v1_api_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*GetEgressEndpointResponse_ResponseNone)(nil),
		(*GetEgressEndpointResponse_ResponseUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafmesh_api_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kafmesh_api_v1_api_proto_goTypes,
		DependencyIndexes: file_kafmesh_api_v1_api_proto_depIdxs,
		MessageInfos:      file_kafmesh_api_v1_api_proto_msgTypes,
	}.Build()
	File_kafmesh_api_v1_api_proto = out.File
	file_kafmesh_api_v1_api_proto_rawDesc = nil
	file_kafmesh_api_v1_api_proto_goTypes = nil
	file_kafmesh_api_v1_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*GetAssignmentResponse, error)
	AssignDevice(ctx context.Context, in *AssignDeviceRequest, opts ...grpc.CallOption) (*AssignDeviceResponse, error)
	UpdateCustomerDetails(ctx context.Context, in *UpdateCustomerDetailsRequest, opts ...grpc.CallOption) (*UpdateCustomerDetailsResponse, error)
	GetCustomerDetails(ctx context.Context, in *GetCustomerDetailsRequest, opts ...grpc.CallOption) (*GetCustomerDetailsResponse, error)
	GetEgressEndpoint(ctx context.Context, in *GetEgressEndpointRequest, opts ...grpc.CallOption) (*GetEgressEndpointResponse, error)
	SetEgressEndpoint(ctx context.Context, in *SetEgressEndpointRequest, opts ...grpc.CallOption) (*SetEgressEndpointResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*GetAssignmentResponse, error) {
	out := new(GetAssignmentResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/GetAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AssignDevice(ctx context.Context, in *AssignDeviceRequest, opts ...grpc.CallOption) (*AssignDeviceResponse, error) {
	out := new(AssignDeviceResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/AssignDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateCustomerDetails(ctx context.Context, in *UpdateCustomerDetailsRequest, opts ...grpc.CallOption) (*UpdateCustomerDetailsResponse, error) {
	out := new(UpdateCustomerDetailsResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/UpdateCustomerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetCustomerDetails(ctx context.Context, in *GetCustomerDetailsRequest, opts ...grpc.CallOption) (*GetCustomerDetailsResponse, error) {
	out := new(GetCustomerDetailsResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/GetCustomerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetEgressEndpoint(ctx context.Context, in *GetEgressEndpointRequest, opts ...grpc.CallOption) (*GetEgressEndpointResponse, error) {
	out := new(GetEgressEndpointResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/GetEgressEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetEgressEndpoint(ctx context.Context, in *SetEgressEndpointRequest, opts ...grpc.CallOption) (*SetEgressEndpointResponse, error) {
	out := new(SetEgressEndpointResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/SetEgressEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	GetAssignment(context.Context, *GetAssignmentRequest) (*GetAssignmentResponse, error)
	AssignDevice(context.Context, *AssignDeviceRequest) (*AssignDeviceResponse, error)
	UpdateCustomerDetails(context.Context, *UpdateCustomerDetailsRequest) (*UpdateCustomerDetailsResponse, error)
	GetCustomerDetails(context.Context, *GetCustomerDetailsRequest) (*GetCustomerDetailsResponse, error)
	GetEgressEndpoint(context.Context, *GetEgressEndpointRequest) (*GetEgressEndpointResponse, error)
	SetEgressEndpoint(context.Context, *SetEgressEndpointRequest) (*SetEgressEndpointResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) GetAssignment(context.Context, *GetAssignmentRequest) (*GetAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignment not implemented")
}
func (*UnimplementedApiServer) AssignDevice(context.Context, *AssignDeviceRequest) (*AssignDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignDevice not implemented")
}
func (*UnimplementedApiServer) UpdateCustomerDetails(context.Context, *UpdateCustomerDetailsRequest) (*UpdateCustomerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomerDetails not implemented")
}
func (*UnimplementedApiServer) GetCustomerDetails(context.Context, *GetCustomerDetailsRequest) (*GetCustomerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerDetails not implemented")
}
func (*UnimplementedApiServer) GetEgressEndpoint(context.Context, *GetEgressEndpointRequest) (*GetEgressEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEgressEndpoint not implemented")
}
func (*UnimplementedApiServer) SetEgressEndpoint(context.Context, *SetEgressEndpointRequest) (*SetEgressEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEgressEndpoint not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/GetAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetAssignment(ctx, req.(*GetAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AssignDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AssignDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/AssignDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AssignDevice(ctx, req.(*AssignDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateCustomerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateCustomerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/UpdateCustomerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateCustomerDetails(ctx, req.(*UpdateCustomerDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetCustomerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetCustomerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/GetCustomerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetCustomerDetails(ctx, req.(*GetCustomerDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetEgressEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEgressEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetEgressEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/GetEgressEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetEgressEndpoint(ctx, req.(*GetEgressEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetEgressEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEgressEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetEgressEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/SetEgressEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetEgressEndpoint(ctx, req.(*SetEgressEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kafmesh.api.v1.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssignment",
			Handler:    _Api_GetAssignment_Handler,
		},
		{
			MethodName: "AssignDevice",
			Handler:    _Api_AssignDevice_Handler,
		},
		{
			MethodName: "UpdateCustomerDetails",
			Handler:    _Api_UpdateCustomerDetails_Handler,
		},
		{
			MethodName: "GetCustomerDetails",
			Handler:    _Api_GetCustomerDetails_Handler,
		},
		{
			MethodName: "GetEgressEndpoint",
			Handler:    _Api_GetEgressEndpoint_Handler,
		},
		{
			MethodName: "SetEgressEndpoint",
			Handler:    _Api_SetEgressEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kafmesh/api/v1/api.proto",
}
