// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/api/v1/api.proto

package apiv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAssignmentRequest struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssignmentRequest) Reset()         { *m = GetAssignmentRequest{} }
func (m *GetAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssignmentRequest) ProtoMessage()    {}
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{0}
}

func (m *GetAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssignmentRequest.Unmarshal(m, b)
}
func (m *GetAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssignmentRequest.Marshal(b, m, deterministic)
}
func (m *GetAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssignmentRequest.Merge(m, src)
}
func (m *GetAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetAssignmentRequest.Size(m)
}
func (m *GetAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssignmentRequest proto.InternalMessageInfo

func (m *GetAssignmentRequest) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type GetAssignmentResponse struct {
	CustomerId           *wrappers.Int64Value `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAssignmentResponse) Reset()         { *m = GetAssignmentResponse{} }
func (m *GetAssignmentResponse) String() string { return proto.CompactTextString(m) }
func (*GetAssignmentResponse) ProtoMessage()    {}
func (*GetAssignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{1}
}

func (m *GetAssignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssignmentResponse.Unmarshal(m, b)
}
func (m *GetAssignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssignmentResponse.Marshal(b, m, deterministic)
}
func (m *GetAssignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssignmentResponse.Merge(m, src)
}
func (m *GetAssignmentResponse) XXX_Size() int {
	return xxx_messageInfo_GetAssignmentResponse.Size(m)
}
func (m *GetAssignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssignmentResponse proto.InternalMessageInfo

func (m *GetAssignmentResponse) GetCustomerId() *wrappers.Int64Value {
	if m != nil {
		return m.CustomerId
	}
	return nil
}

type AssignDeviceRequest struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignDeviceRequest) Reset()         { *m = AssignDeviceRequest{} }
func (m *AssignDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*AssignDeviceRequest) ProtoMessage()    {}
func (*AssignDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{2}
}

func (m *AssignDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignDeviceRequest.Unmarshal(m, b)
}
func (m *AssignDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignDeviceRequest.Marshal(b, m, deterministic)
}
func (m *AssignDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignDeviceRequest.Merge(m, src)
}
func (m *AssignDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_AssignDeviceRequest.Size(m)
}
func (m *AssignDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignDeviceRequest proto.InternalMessageInfo

func (m *AssignDeviceRequest) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *AssignDeviceRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

type AssignDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignDeviceResponse) Reset()         { *m = AssignDeviceResponse{} }
func (m *AssignDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*AssignDeviceResponse) ProtoMessage()    {}
func (*AssignDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{3}
}

func (m *AssignDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignDeviceResponse.Unmarshal(m, b)
}
func (m *AssignDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignDeviceResponse.Marshal(b, m, deterministic)
}
func (m *AssignDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignDeviceResponse.Merge(m, src)
}
func (m *AssignDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_AssignDeviceResponse.Size(m)
}
func (m *AssignDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignDeviceResponse proto.InternalMessageInfo

type UpdateCustomerDetailsRequest struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerDetailsRequest) Reset()         { *m = UpdateCustomerDetailsRequest{} }
func (m *UpdateCustomerDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerDetailsRequest) ProtoMessage()    {}
func (*UpdateCustomerDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{4}
}

func (m *UpdateCustomerDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerDetailsRequest.Unmarshal(m, b)
}
func (m *UpdateCustomerDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerDetailsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerDetailsRequest.Merge(m, src)
}
func (m *UpdateCustomerDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerDetailsRequest.Size(m)
}
func (m *UpdateCustomerDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerDetailsRequest proto.InternalMessageInfo

func (m *UpdateCustomerDetailsRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *UpdateCustomerDetailsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateCustomerDetailsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerDetailsResponse) Reset()         { *m = UpdateCustomerDetailsResponse{} }
func (m *UpdateCustomerDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerDetailsResponse) ProtoMessage()    {}
func (*UpdateCustomerDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{5}
}

func (m *UpdateCustomerDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerDetailsResponse.Unmarshal(m, b)
}
func (m *UpdateCustomerDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerDetailsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerDetailsResponse.Merge(m, src)
}
func (m *UpdateCustomerDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerDetailsResponse.Size(m)
}
func (m *UpdateCustomerDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerDetailsResponse proto.InternalMessageInfo

type GetCustomerDetailsRequest struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerDetailsRequest) Reset()         { *m = GetCustomerDetailsRequest{} }
func (m *GetCustomerDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerDetailsRequest) ProtoMessage()    {}
func (*GetCustomerDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{6}
}

func (m *GetCustomerDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerDetailsRequest.Unmarshal(m, b)
}
func (m *GetCustomerDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerDetailsRequest.Merge(m, src)
}
func (m *GetCustomerDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerDetailsRequest.Size(m)
}
func (m *GetCustomerDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerDetailsRequest proto.InternalMessageInfo

func (m *GetCustomerDetailsRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

type GetCustomerDetailsResponse struct {
	Name                 *wrappers.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetCustomerDetailsResponse) Reset()         { *m = GetCustomerDetailsResponse{} }
func (m *GetCustomerDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerDetailsResponse) ProtoMessage()    {}
func (*GetCustomerDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_703581f022bd0c53, []int{7}
}

func (m *GetCustomerDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerDetailsResponse.Unmarshal(m, b)
}
func (m *GetCustomerDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerDetailsResponse.Merge(m, src)
}
func (m *GetCustomerDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerDetailsResponse.Size(m)
}
func (m *GetCustomerDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerDetailsResponse proto.InternalMessageInfo

func (m *GetCustomerDetailsResponse) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAssignmentRequest)(nil), "kafmesh.api.v1.GetAssignmentRequest")
	proto.RegisterType((*GetAssignmentResponse)(nil), "kafmesh.api.v1.GetAssignmentResponse")
	proto.RegisterType((*AssignDeviceRequest)(nil), "kafmesh.api.v1.AssignDeviceRequest")
	proto.RegisterType((*AssignDeviceResponse)(nil), "kafmesh.api.v1.AssignDeviceResponse")
	proto.RegisterType((*UpdateCustomerDetailsRequest)(nil), "kafmesh.api.v1.UpdateCustomerDetailsRequest")
	proto.RegisterType((*UpdateCustomerDetailsResponse)(nil), "kafmesh.api.v1.UpdateCustomerDetailsResponse")
	proto.RegisterType((*GetCustomerDetailsRequest)(nil), "kafmesh.api.v1.GetCustomerDetailsRequest")
	proto.RegisterType((*GetCustomerDetailsResponse)(nil), "kafmesh.api.v1.GetCustomerDetailsResponse")
}

func init() { proto.RegisterFile("kafmesh/api/v1/api.proto", fileDescriptor_703581f022bd0c53) }

var fileDescriptor_703581f022bd0c53 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x5f, 0xaf, 0xd2, 0x30,
	0x1c, 0xcd, 0xbd, 0xa8, 0xf1, 0xfe, 0xae, 0xde, 0x87, 0x0a, 0x06, 0x07, 0x8a, 0x99, 0x98, 0xa8,
	0xd1, 0xce, 0x81, 0xf1, 0x89, 0x17, 0x94, 0x84, 0x10, 0x13, 0x1f, 0x46, 0x20, 0xd1, 0x98, 0x98,
	0xc2, 0x7e, 0xcc, 0x06, 0xb6, 0xd5, 0xb5, 0x9b, 0x9f, 0xc7, 0x57, 0x3f, 0xa5, 0x61, 0xed, 0x12,
	0x06, 0x03, 0x89, 0x4f, 0x90, 0xf6, 0xfc, 0xdb, 0x39, 0x85, 0xe6, 0x9a, 0xad, 0x42, 0x94, 0x3f,
	0x1c, 0x26, 0xb8, 0x93, 0xb9, 0xdb, 0x1f, 0x2a, 0x92, 0x58, 0xc5, 0xe4, 0xc6, 0xdc, 0xd0, 0xed,
	0x51, 0xe6, 0x5a, 0x4f, 0x82, 0x38, 0x0e, 0x36, 0xe8, 0xe4, 0xb7, 0x8b, 0x74, 0xe5, 0xfc, 0x4a,
	0x98, 0x10, 0x98, 0x48, 0x8d, 0xb7, 0xfb, 0x50, 0x1f, 0xa3, 0x1a, 0x4a, 0xc9, 0x83, 0x28, 0xc4,
	0x48, 0x79, 0xf8, 0x33, 0x45, 0xa9, 0x48, 0x0b, 0xae, 0x7c, 0xcc, 0xf8, 0x12, 0xbf, 0x73, 0xbf,
	0x79, 0xf1, 0xf4, 0xe2, 0x45, 0xcd, 0xbb, 0xab, 0x0f, 0x26, 0xbe, 0x3d, 0x83, 0xc6, 0x1e, 0x49,
	0x8a, 0x38, 0x92, 0x48, 0x06, 0x70, 0xbd, 0x4c, 0xa5, 0x8a, 0x43, 0x4c, 0x0a, 0xde, 0x75, 0xaf,
	0x45, 0x75, 0x06, 0x5a, 0x64, 0xa0, 0x93, 0x48, 0xbd, 0x7f, 0x37, 0x67, 0x9b, 0x14, 0x3d, 0x28,
	0xf0, 0x13, 0xdf, 0x9e, 0xc2, 0x03, 0xad, 0x39, 0xca, 0x8d, 0xce, 0x89, 0x42, 0x3a, 0x65, 0xc7,
	0xcb, 0xfc, 0x7a, 0x57, 0xf4, 0x21, 0xd4, 0xcb, 0xa2, 0x3a, 0xaa, 0x3d, 0x85, 0xf6, 0x4c, 0xf8,
	0x4c, 0xe1, 0x47, 0x83, 0x1d, 0xa1, 0x62, 0x7c, 0x23, 0x0b, 0xd7, 0xce, 0xe1, 0xa7, 0x94, 0x84,
	0x09, 0x81, 0x5b, 0x11, 0x0b, 0x31, 0xb7, 0xbc, 0xf2, 0xf2, 0xff, 0x76, 0x07, 0x1e, 0x1f, 0x11,
	0x35, 0xae, 0x03, 0x78, 0x34, 0x46, 0xf5, 0x9f, 0x96, 0xf6, 0x67, 0xb0, 0xaa, 0xd8, 0xa6, 0xfc,
	0xb7, 0x26, 0x90, 0x6e, 0xbd, 0x7d, 0xd0, 0xfa, 0x54, 0x25, 0x3c, 0x0a, 0x74, 0xed, 0x39, 0xb2,
	0xf7, 0xbb, 0x06, 0xb5, 0xa1, 0xe0, 0xe4, 0x1b, 0xdc, 0x2f, 0xed, 0x49, 0xba, 0xb4, 0xfc, 0x8c,
	0x68, 0xd5, 0x1b, 0xb1, 0x9e, 0xff, 0x03, 0x65, 0x72, 0x7d, 0x81, 0x7b, 0xbb, 0x0b, 0x90, 0x67,
	0xfb, 0xb4, 0x8a, 0xd1, 0xad, 0xee, 0x69, 0x90, 0x91, 0x56, 0xd0, 0xa8, 0xec, 0x9b, 0xbc, 0xde,
	0xa7, 0x9f, 0xda, 0xda, 0x7a, 0x73, 0x26, 0xda, 0xb8, 0xae, 0x81, 0x1c, 0xce, 0x40, 0x5e, 0x56,
	0xb4, 0x71, 0xc4, 0xef, 0xd5, 0x39, 0x50, 0x6d, 0xf6, 0xa1, 0xf9, 0xf5, 0x36, 0x13, 0x3c, 0x73,
	0xff, 0x5c, 0xde, 0x7c, 0x32, 0xa4, 0xa1, 0xe0, 0x74, 0xee, 0x2e, 0xee, 0xe4, 0xcb, 0xf6, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x22, 0x11, 0x96, 0x01, 0x0d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*GetAssignmentResponse, error)
	AssignDevice(ctx context.Context, in *AssignDeviceRequest, opts ...grpc.CallOption) (*AssignDeviceResponse, error)
	UpdateCustomerDetails(ctx context.Context, in *UpdateCustomerDetailsRequest, opts ...grpc.CallOption) (*UpdateCustomerDetailsResponse, error)
	GetCustomerDetails(ctx context.Context, in *GetCustomerDetailsRequest, opts ...grpc.CallOption) (*GetCustomerDetailsResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*GetAssignmentResponse, error) {
	out := new(GetAssignmentResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/GetAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AssignDevice(ctx context.Context, in *AssignDeviceRequest, opts ...grpc.CallOption) (*AssignDeviceResponse, error) {
	out := new(AssignDeviceResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/AssignDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateCustomerDetails(ctx context.Context, in *UpdateCustomerDetailsRequest, opts ...grpc.CallOption) (*UpdateCustomerDetailsResponse, error) {
	out := new(UpdateCustomerDetailsResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/UpdateCustomerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetCustomerDetails(ctx context.Context, in *GetCustomerDetailsRequest, opts ...grpc.CallOption) (*GetCustomerDetailsResponse, error) {
	out := new(GetCustomerDetailsResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.api.v1.Api/GetCustomerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	GetAssignment(context.Context, *GetAssignmentRequest) (*GetAssignmentResponse, error)
	AssignDevice(context.Context, *AssignDeviceRequest) (*AssignDeviceResponse, error)
	UpdateCustomerDetails(context.Context, *UpdateCustomerDetailsRequest) (*UpdateCustomerDetailsResponse, error)
	GetCustomerDetails(context.Context, *GetCustomerDetailsRequest) (*GetCustomerDetailsResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) GetAssignment(ctx context.Context, req *GetAssignmentRequest) (*GetAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignment not implemented")
}
func (*UnimplementedApiServer) AssignDevice(ctx context.Context, req *AssignDeviceRequest) (*AssignDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignDevice not implemented")
}
func (*UnimplementedApiServer) UpdateCustomerDetails(ctx context.Context, req *UpdateCustomerDetailsRequest) (*UpdateCustomerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomerDetails not implemented")
}
func (*UnimplementedApiServer) GetCustomerDetails(ctx context.Context, req *GetCustomerDetailsRequest) (*GetCustomerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerDetails not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/GetAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetAssignment(ctx, req.(*GetAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AssignDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AssignDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/AssignDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AssignDevice(ctx, req.(*AssignDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateCustomerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateCustomerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/UpdateCustomerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateCustomerDetails(ctx, req.(*UpdateCustomerDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetCustomerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetCustomerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.api.v1.Api/GetCustomerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetCustomerDetails(ctx, req.(*GetCustomerDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kafmesh.api.v1.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssignment",
			Handler:    _Api_GetAssignment_Handler,
		},
		{
			MethodName: "AssignDevice",
			Handler:    _Api_AssignDevice_Handler,
		},
		{
			MethodName: "UpdateCustomerDetails",
			Handler:    _Api_UpdateCustomerDetails_Handler,
		},
		{
			MethodName: "GetCustomerDetails",
			Handler:    _Api_GetCustomerDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kafmesh/api/v1/api.proto",
}
