// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/deviceId/enriched_heartbeat.proto

package kafmesh_deviceId

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnrichedHeartbeat struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrichedHeartbeat) Reset()         { *m = EnrichedHeartbeat{} }
func (m *EnrichedHeartbeat) String() string { return proto.CompactTextString(m) }
func (*EnrichedHeartbeat) ProtoMessage()    {}
func (*EnrichedHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a30101a0a5fdf64, []int{0}
}

func (m *EnrichedHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrichedHeartbeat.Unmarshal(m, b)
}
func (m *EnrichedHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrichedHeartbeat.Marshal(b, m, deterministic)
}
func (m *EnrichedHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrichedHeartbeat.Merge(m, src)
}
func (m *EnrichedHeartbeat) XXX_Size() int {
	return xxx_messageInfo_EnrichedHeartbeat.Size(m)
}
func (m *EnrichedHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrichedHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_EnrichedHeartbeat proto.InternalMessageInfo

func (m *EnrichedHeartbeat) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*EnrichedHeartbeat)(nil), "kafmesh.deviceId.EnrichedHeartbeat")
}

func init() {
	proto.RegisterFile("kafmesh/deviceId/enriched_heartbeat.proto", fileDescriptor_0a30101a0a5fdf64)
}

var fileDescriptor_0a30101a0a5fdf64 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcc, 0x4e, 0x4c, 0xcb,
	0x4d, 0x2d, 0xce, 0xd0, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xf5, 0x4c, 0xd1, 0x4f, 0xcd, 0x2b,
	0xca, 0x4c, 0xce, 0x48, 0x4d, 0x89, 0xcf, 0x48, 0x4d, 0x2c, 0x2a, 0x49, 0x4a, 0x4d, 0x2c, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x2a, 0xd5, 0x83, 0x29, 0x55, 0x52, 0xe7, 0x12,
	0x74, 0x85, 0xaa, 0xf6, 0x80, 0x29, 0x16, 0x12, 0xe2, 0x62, 0x29, 0xc9, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0x26, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xad, 0xbc, 0x5c, 0xc9, 0x6e, 0x00, 0x00, 0x00,
}
