// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/deviceId/enriched_details_state.proto

package kafmesh_deviceId

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnrichedDetailsState struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrichedDetailsState) Reset()         { *m = EnrichedDetailsState{} }
func (m *EnrichedDetailsState) String() string { return proto.CompactTextString(m) }
func (*EnrichedDetailsState) ProtoMessage()    {}
func (*EnrichedDetailsState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4d33a708691e224, []int{0}
}

func (m *EnrichedDetailsState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrichedDetailsState.Unmarshal(m, b)
}
func (m *EnrichedDetailsState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrichedDetailsState.Marshal(b, m, deterministic)
}
func (m *EnrichedDetailsState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrichedDetailsState.Merge(m, src)
}
func (m *EnrichedDetailsState) XXX_Size() int {
	return xxx_messageInfo_EnrichedDetailsState.Size(m)
}
func (m *EnrichedDetailsState) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrichedDetailsState.DiscardUnknown(m)
}

var xxx_messageInfo_EnrichedDetailsState proto.InternalMessageInfo

func (m *EnrichedDetailsState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*EnrichedDetailsState)(nil), "kafmesh.deviceId.EnrichedDetailsState")
}

func init() {
	proto.RegisterFile("kafmesh/deviceId/enriched_details_state.proto", fileDescriptor_e4d33a708691e224)
}

var fileDescriptor_e4d33a708691e224 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcd, 0x4e, 0x4c, 0xcb,
	0x4d, 0x2d, 0xce, 0xd0, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xf5, 0x4c, 0xd1, 0x4f, 0xcd, 0x2b,
	0xca, 0x4c, 0xce, 0x48, 0x4d, 0x89, 0x4f, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0x29, 0x8e, 0x2f, 0x2e,
	0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x2a, 0xd7, 0x83, 0x29,
	0x57, 0xd2, 0xe2, 0x12, 0x71, 0x85, 0xea, 0x70, 0x81, 0x68, 0x08, 0x06, 0xa9, 0x17, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8,
	0xc0, 0x86, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xd5, 0x1b, 0xcb, 0x75, 0x00, 0x00,
	0x00,
}
