// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/deviceId/enriched_details.proto

package kafmesh_deviceId

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnrichedDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrichedDetails) Reset()         { *m = EnrichedDetails{} }
func (m *EnrichedDetails) String() string { return proto.CompactTextString(m) }
func (*EnrichedDetails) ProtoMessage()    {}
func (*EnrichedDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d16f8ec54ff093, []int{0}
}

func (m *EnrichedDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrichedDetails.Unmarshal(m, b)
}
func (m *EnrichedDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrichedDetails.Marshal(b, m, deterministic)
}
func (m *EnrichedDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrichedDetails.Merge(m, src)
}
func (m *EnrichedDetails) XXX_Size() int {
	return xxx_messageInfo_EnrichedDetails.Size(m)
}
func (m *EnrichedDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrichedDetails.DiscardUnknown(m)
}

var xxx_messageInfo_EnrichedDetails proto.InternalMessageInfo

func (m *EnrichedDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*EnrichedDetails)(nil), "kafmesh.deviceId.EnrichedDetails")
}

func init() {
	proto.RegisterFile("kafmesh/deviceId/enriched_details.proto", fileDescriptor_34d16f8ec54ff093)
}

var fileDescriptor_34d16f8ec54ff093 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcf, 0x4e, 0x4c, 0xcb,
	0x4d, 0x2d, 0xce, 0xd0, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xf5, 0x4c, 0xd1, 0x4f, 0xcd, 0x2b,
	0xca, 0x4c, 0xce, 0x48, 0x4d, 0x89, 0x4f, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0x29, 0xd6, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x2a, 0xd4, 0x83, 0x29, 0x54, 0x52, 0xe5, 0xe2, 0x77, 0x85,
	0xaa, 0x75, 0x81, 0x28, 0x15, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xfa, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x97, 0x85, 0x97, 0xb2, 0x6a, 0x00, 0x00, 0x00,
}
