// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/syncromatics/kafmesh-example/internal/definitions/egress/customerId_egressEndpoint_viewSource.km.go

// Package egress is a generated GoMock package.
package egress

import (
	gomock "github.com/golang/mock/gomock"
	customerId "kafmesh-example/internal/definitions/models/kafmesh/customerId"
	reflect "reflect"
	time "time"
)

// MockEgress_ViewSource_Context is a mock of Egress_ViewSource_Context interface
type MockEgress_ViewSource_Context struct {
	ctrl     *gomock.Controller
	recorder *MockEgress_ViewSource_ContextMockRecorder
}

// MockEgress_ViewSource_ContextMockRecorder is the mock recorder for MockEgress_ViewSource_Context
type MockEgress_ViewSource_ContextMockRecorder struct {
	mock *MockEgress_ViewSource_Context
}

// NewMockEgress_ViewSource_Context creates a new mock instance
func NewMockEgress_ViewSource_Context(ctrl *gomock.Controller) *MockEgress_ViewSource_Context {
	mock := &MockEgress_ViewSource_Context{ctrl: ctrl}
	mock.recorder = &MockEgress_ViewSource_ContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEgress_ViewSource_Context) EXPECT() *MockEgress_ViewSource_ContextMockRecorder {
	return m.recorder
}

// Deadline mocks base method
func (m *MockEgress_ViewSource_Context) Deadline() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline
func (mr *MockEgress_ViewSource_ContextMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockEgress_ViewSource_Context)(nil).Deadline))
}

// Done mocks base method
func (m *MockEgress_ViewSource_Context) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done
func (mr *MockEgress_ViewSource_ContextMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockEgress_ViewSource_Context)(nil).Done))
}

// Err mocks base method
func (m *MockEgress_ViewSource_Context) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err
func (mr *MockEgress_ViewSource_ContextMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockEgress_ViewSource_Context)(nil).Err))
}

// Value mocks base method
func (m *MockEgress_ViewSource_Context) Value(key interface{}) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", key)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// Value indicates an expected call of Value
func (mr *MockEgress_ViewSource_ContextMockRecorder) Value(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockEgress_ViewSource_Context)(nil).Value), key)
}

// Update mocks base method
func (m *MockEgress_ViewSource_Context) Update(arg0 string, arg1 *customerId.EgressEndpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockEgress_ViewSource_ContextMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEgress_ViewSource_Context)(nil).Update), arg0, arg1)
}

// MockEgress_ViewSource is a mock of Egress_ViewSource interface
type MockEgress_ViewSource struct {
	ctrl     *gomock.Controller
	recorder *MockEgress_ViewSourceMockRecorder
}

// MockEgress_ViewSourceMockRecorder is the mock recorder for MockEgress_ViewSource
type MockEgress_ViewSourceMockRecorder struct {
	mock *MockEgress_ViewSource
}

// NewMockEgress_ViewSource creates a new mock instance
func NewMockEgress_ViewSource(ctrl *gomock.Controller) *MockEgress_ViewSource {
	mock := &MockEgress_ViewSource{ctrl: ctrl}
	mock.recorder = &MockEgress_ViewSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEgress_ViewSource) EXPECT() *MockEgress_ViewSourceMockRecorder {
	return m.recorder
}

// Sync mocks base method
func (m *MockEgress_ViewSource) Sync(arg0 Egress_ViewSource_Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync
func (mr *MockEgress_ViewSourceMockRecorder) Sync(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockEgress_ViewSource)(nil).Sync), arg0)
}
