// Code generated by MockGen. DO NOT EDIT.
// Source: ./warehouseSink.go

// Package heartbeats_test is a generated GoMock package.
package heartbeats_test

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	warehouse "kafmesh-example/internal/warehouse"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SaveHeartbeats mocks base method
func (m *MockRepository) SaveHeartbeats(arg0 context.Context, arg1 []warehouse.Heartbeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHeartbeats", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveHeartbeats indicates an expected call of SaveHeartbeats
func (mr *MockRepositoryMockRecorder) SaveHeartbeats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHeartbeats", reflect.TypeOf((*MockRepository)(nil).SaveHeartbeats), arg0, arg1)
}
