// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/syncromatics/kafmesh-example/internal/definitions/assignments/deviceId_customer_source.km.go

// Package assignments is a generated GoMock package.
package assignments

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDeviceIDCustomer_Source is a mock of DeviceIDCustomer_Source interface
type MockDeviceIDCustomer_Source struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceIDCustomer_SourceMockRecorder
}

// MockDeviceIDCustomer_SourceMockRecorder is the mock recorder for MockDeviceIDCustomer_Source
type MockDeviceIDCustomer_SourceMockRecorder struct {
	mock *MockDeviceIDCustomer_Source
}

// NewMockDeviceIDCustomer_Source creates a new mock instance
func NewMockDeviceIDCustomer_Source(ctrl *gomock.Controller) *MockDeviceIDCustomer_Source {
	mock := &MockDeviceIDCustomer_Source{ctrl: ctrl}
	mock.recorder = &MockDeviceIDCustomer_SourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeviceIDCustomer_Source) EXPECT() *MockDeviceIDCustomer_SourceMockRecorder {
	return m.recorder
}

// Emit mocks base method
func (m *MockDeviceIDCustomer_Source) Emit(message DeviceIDCustomer_Source_Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Emit indicates an expected call of Emit
func (mr *MockDeviceIDCustomer_SourceMockRecorder) Emit(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockDeviceIDCustomer_Source)(nil).Emit), message)
}

// EmitBulk mocks base method
func (m *MockDeviceIDCustomer_Source) EmitBulk(ctx context.Context, messages []DeviceIDCustomer_Source_Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitBulk", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitBulk indicates an expected call of EmitBulk
func (mr *MockDeviceIDCustomer_SourceMockRecorder) EmitBulk(ctx, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitBulk", reflect.TypeOf((*MockDeviceIDCustomer_Source)(nil).EmitBulk), ctx, messages)
}

// Delete mocks base method
func (m *MockDeviceIDCustomer_Source) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDeviceIDCustomer_SourceMockRecorder) Delete(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceIDCustomer_Source)(nil).Delete), key)
}
