// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/kafmesh-example/internal/definitions/assignments/kafmesh_deviceId_customer_view.km.go

// Package assignments is a generated GoMock package.
package assignments

import (
	gomock "github.com/golang/mock/gomock"
	deviceId "kafmesh-example/internal/definitions/models/kafmesh/deviceId"
	reflect "reflect"
)

// MockKafmeshDeviceIDCustomer_View is a mock of KafmeshDeviceIDCustomer_View interface
type MockKafmeshDeviceIDCustomer_View struct {
	ctrl     *gomock.Controller
	recorder *MockKafmeshDeviceIDCustomer_ViewMockRecorder
}

// MockKafmeshDeviceIDCustomer_ViewMockRecorder is the mock recorder for MockKafmeshDeviceIDCustomer_View
type MockKafmeshDeviceIDCustomer_ViewMockRecorder struct {
	mock *MockKafmeshDeviceIDCustomer_View
}

// NewMockKafmeshDeviceIDCustomer_View creates a new mock instance
func NewMockKafmeshDeviceIDCustomer_View(ctrl *gomock.Controller) *MockKafmeshDeviceIDCustomer_View {
	mock := &MockKafmeshDeviceIDCustomer_View{ctrl: ctrl}
	mock.recorder = &MockKafmeshDeviceIDCustomer_ViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKafmeshDeviceIDCustomer_View) EXPECT() *MockKafmeshDeviceIDCustomer_ViewMockRecorder {
	return m.recorder
}

// Keys mocks base method
func (m *MockKafmeshDeviceIDCustomer_View) Keys() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Keys indicates an expected call of Keys
func (mr *MockKafmeshDeviceIDCustomer_ViewMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockKafmeshDeviceIDCustomer_View)(nil).Keys))
}

// Get mocks base method
func (m *MockKafmeshDeviceIDCustomer_View) Get(key string) (*deviceId.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*deviceId.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockKafmeshDeviceIDCustomer_ViewMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKafmeshDeviceIDCustomer_View)(nil).Get), key)
}
