// Code generated by kafmesh-gen. DO NOT EDIT.

package assignments

import (
	"context"

	"github.com/burdiyan/kafkautil"
	"github.com/lovoo/goka"
	"github.com/pkg/errors"

	"github.com/syncromatics/kafmesh/pkg/runner"

	customerId "kafmesh-example/internal/definitions/models/kafmesh/customerId"
)

type CustomerIdDetails_Emitter interface {
	Emit(message CustomerIdDetails_Emitter_Message) error
	EmitBulk(ctx context.Context, messages []CustomerIdDetails_Emitter_Message) error
}

type CustomerIdDetails_Emitter_impl struct {
	emitter *runner.Emitter
}

type CustomerIdDetails_Emitter_Message struct {
	Key string
	Value *customerId.Details
}

type impl_CustomerIdDetails_Emitter_Message struct {
	msg CustomerIdDetails_Emitter_Message
}

func (m *impl_CustomerIdDetails_Emitter_Message) Key() string {
	return m.msg.Key
}

func (m *impl_CustomerIdDetails_Emitter_Message) Value() interface{} {
	return m.msg.Value
}

func New_CustomerIdDetails_Emitter(options runner.ServiceOptions) (*CustomerIdDetails_Emitter_impl, error) {
	brokers := options.Brokers
	protoWrapper := options.ProtoWrapper

	codec, err := protoWrapper.Codec("kafmesh.customerId.details", &customerId.Details{})
	if err != nil {
		return nil, errors.Wrap(err, "failed to create codec")
	}

	emitter, err := goka.NewEmitter(brokers,
		goka.Stream("kafmesh.customerId.details"),
		codec,
		goka.WithEmitterHasher(kafkautil.MurmurHasher))

	if err != nil {
		return nil, errors.Wrap(err, "failed creating emitter")
	}

	return &CustomerIdDetails_Emitter_impl{
		emitter: runner.NewEmitter(emitter),
	}, nil
}

func (e *CustomerIdDetails_Emitter_impl) Watch(ctx context.Context) func() error {
	return e.emitter.Watch(ctx)
}

func (e *CustomerIdDetails_Emitter_impl) Emit(message CustomerIdDetails_Emitter_Message) error {
	return e.emitter.Emit(message.Key, message.Value)
}

func (e *CustomerIdDetails_Emitter_impl) EmitBulk(ctx context.Context, messages []CustomerIdDetails_Emitter_Message) error {
	b := []runner.EmitMessage{}
	for _, m := range messages {
		b = append(b, &impl_CustomerIdDetails_Emitter_Message{msg: m})
	}
	return e.emitter.EmitBulk(ctx, b)
}
