// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/kafmesh-example/internal/definitions/assignments/kafmesh_customerId_details_view.km.go

// Package assignments is a generated GoMock package.
package assignments

import (
	gomock "github.com/golang/mock/gomock"
	customerId "kafmesh-example/internal/definitions/models/kafmesh/customerId"
	reflect "reflect"
)

// MockKafmeshCustomerIDDetails_View is a mock of KafmeshCustomerIDDetails_View interface
type MockKafmeshCustomerIDDetails_View struct {
	ctrl     *gomock.Controller
	recorder *MockKafmeshCustomerIDDetails_ViewMockRecorder
}

// MockKafmeshCustomerIDDetails_ViewMockRecorder is the mock recorder for MockKafmeshCustomerIDDetails_View
type MockKafmeshCustomerIDDetails_ViewMockRecorder struct {
	mock *MockKafmeshCustomerIDDetails_View
}

// NewMockKafmeshCustomerIDDetails_View creates a new mock instance
func NewMockKafmeshCustomerIDDetails_View(ctrl *gomock.Controller) *MockKafmeshCustomerIDDetails_View {
	mock := &MockKafmeshCustomerIDDetails_View{ctrl: ctrl}
	mock.recorder = &MockKafmeshCustomerIDDetails_ViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKafmeshCustomerIDDetails_View) EXPECT() *MockKafmeshCustomerIDDetails_ViewMockRecorder {
	return m.recorder
}

// Keys mocks base method
func (m *MockKafmeshCustomerIDDetails_View) Keys() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Keys indicates an expected call of Keys
func (mr *MockKafmeshCustomerIDDetails_ViewMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockKafmeshCustomerIDDetails_View)(nil).Keys))
}

// Get mocks base method
func (m *MockKafmeshCustomerIDDetails_View) Get(key string) (*customerId.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*customerId.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockKafmeshCustomerIDDetails_ViewMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKafmeshCustomerIDDetails_View)(nil).Get), key)
}
