// Code generated by kafmesh-gen. DO NOT EDIT.

package details

import (
	"context"
	"os"
	"path/filepath"

	"github.com/burdiyan/kafkautil"
	"github.com/lovoo/goka"
	"github.com/lovoo/goka/storage"
	"github.com/pkg/errors"
	"github.com/syndtr/goleveldb/leveldb/opt"

	"github.com/syncromatics/kafmesh/pkg/runner"

	deviceId "kafmesh-example/internal/kafmesh/definitions/models/kafmesh/deviceId"
)

type DeviceIdEnrichedDetails_View struct {
	view *goka.View
}

func New_DeviceIdEnrichedDetails_View(options runner.ServiceOptions) (*DeviceIdEnrichedDetails_View, error) {
	brokers := options.Brokers
	protoWrapper := options.ProtoWrapper

	codec, err := protoWrapper.Codec("kafmesh.deviceId.enrichedDetails", &deviceId.EnrichedDetails{})
	if err != nil {
		return nil, errors.Wrap(err, "failed to create codec")
	}

	opts := &opt.Options{
		BlockCacheCapacity: opt.MiB * 1,
		WriteBuffer:        opt.MiB * 1,
	}

	path := filepath.Join("/tmp/storage", "view", "kafmesh.deviceId.enrichedDetails")

	err = os.MkdirAll(path, os.ModePerm)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create view db directory")
	}

	builder := storage.BuilderWithOptions(path, opts)

	view, err := goka.NewView(brokers,
		goka.Table("kafmesh.deviceId.enrichedDetails"),
		codec,
		goka.WithViewStorageBuilder(builder),
		goka.WithViewHasher(kafkautil.MurmurHasher),
	)

	if err != nil {
		return nil, errors.Wrap(err, "failed creating view")
	}

	return &DeviceIdEnrichedDetails_View{
		view: view,
	}, nil
}

func (v *DeviceIdEnrichedDetails_View) Watch(ctx context.Context) func() error {
	return func() error {
		return v.view.Run(ctx)
	}
}

func (v *DeviceIdEnrichedDetails_View) Keys() []string {
	return v.Keys()
}

func (v *DeviceIdEnrichedDetails_View) Get(key string) (*deviceId.EnrichedDetails, error) {
	m, err := v.view.Get(key)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get value from view")
	}

	msg, ok := m.(*deviceId.EnrichedDetails)
	if !ok {
		return nil, errors.Errorf("expecting message of type '*deviceId.EnrichedDetails' got type '%t'", m)
	}

	return msg, nil
}
