// Code generated by MockGen. DO NOT EDIT.
// Source: ./warehouseSink.go

// Package details_test is a generated GoMock package.
package details_test

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	warehouse "kafmesh-example/internal/warehouse"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SaveDetails mocks base method
func (m *MockRepository) SaveDetails(ctx context.Context, details []warehouse.Details) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDetails", ctx, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDetails indicates an expected call of SaveDetails
func (mr *MockRepositoryMockRecorder) SaveDetails(ctx, details interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDetails", reflect.TypeOf((*MockRepository)(nil).SaveDetails), ctx, details)
}
