// Code generated by MockGen. DO NOT EDIT.
// Source: ./deviceCustomerSink.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	data "kafmesh-example/internal/data"
	reflect "reflect"
)

// MockassignmentRepo is a mock of assignmentRepo interface
type MockassignmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockassignmentRepoMockRecorder
}

// MockassignmentRepoMockRecorder is the mock recorder for MockassignmentRepo
type MockassignmentRepoMockRecorder struct {
	mock *MockassignmentRepo
}

// NewMockassignmentRepo creates a new mock instance
func NewMockassignmentRepo(ctrl *gomock.Controller) *MockassignmentRepo {
	mock := &MockassignmentRepo{ctrl: ctrl}
	mock.recorder = &MockassignmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockassignmentRepo) EXPECT() *MockassignmentRepoMockRecorder {
	return m.recorder
}

// GetDeviceAssignments mocks base method
func (m *MockassignmentRepo) GetDeviceAssignments(arg0 context.Context) ([]data.DeviceAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceAssignments", arg0)
	ret0, _ := ret[0].([]data.DeviceAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceAssignments indicates an expected call of GetDeviceAssignments
func (mr *MockassignmentRepoMockRecorder) GetDeviceAssignments(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceAssignments", reflect.TypeOf((*MockassignmentRepo)(nil).GetDeviceAssignments), arg0)
}
