// Code generated by kafmesh-gen. DO NOT EDIT.

package synchronizers

import (
	"context"
	"os"
	"path/filepath"
	"time"

	"github.com/burdiyan/kafkautil"
	"github.com/lovoo/goka"
	"github.com/lovoo/goka/storage"
	"github.com/pkg/errors"
	"github.com/syndtr/goleveldb/leveldb/opt"
	"golang.org/x/sync/errgroup"

	"github.com/syncromatics/kafmesh/pkg/runner"

	deviceId "kafmesh-example/internal/kafmesh/definitions/models/kafmesh/deviceId"
)

type DeviceIdCustomer_Synchronizer_Message struct {
	key string
	value *deviceId.Customer
}

func New_DeviceIdCustomer_Synchronizer_Message(key string, value *deviceId.Customer) *DeviceIdCustomer_Synchronizer_Message {
	return &DeviceIdCustomer_Synchronizer_Message{
		key: key,
		value: value,
	}
}

func (m *DeviceIdCustomer_Synchronizer_Message) Key() string {
	return m.key
}

func (m *DeviceIdCustomer_Synchronizer_Message) Value() interface{} {
	return m.value
}

type DeviceIdCustomer_Synchronizer_Context interface {
	Keys() ([]string, error)
	Get(string) (*deviceId.Customer, error)
	Emit(*DeviceIdCustomer_Synchronizer_Message) error
	EmitBulk(context.Context, []*DeviceIdCustomer_Synchronizer_Message) error
}

type DeviceIdCustomer_Synchronizer_Context_impl struct {
	view *goka.View
	emitter *runner.Emitter
}

func (c *DeviceIdCustomer_Synchronizer_Context_impl) Keys() ([]string, error) {
	it, err := c.view.Iterator()
	if err != nil {
		return nil, errors.Wrap(err, "failed to get iterator")
	}

	keys := []string{}
	for it.Next() {
		keys = append(keys, it.Key())
	}

	return keys, nil
}

func (c *DeviceIdCustomer_Synchronizer_Context_impl) Get(key string) (*deviceId.Customer, error) {
	m, err := c.view.Get(key)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get value from view")
	}

	msg, ok := m.(*deviceId.Customer)
	if !ok {
		return nil, errors.Errorf("expecting message of type '*deviceId.Customer' got type '%t'", m)
	}

	return msg, nil
}

func (c *DeviceIdCustomer_Synchronizer_Context_impl) Emit(message *DeviceIdCustomer_Synchronizer_Message) error {
	return c.emitter.Emit(message.Key(), message.Value())
}

func (c *DeviceIdCustomer_Synchronizer_Context_impl) EmitBulk(ctx context.Context, messages []*DeviceIdCustomer_Synchronizer_Message) error {
	b := []runner.EmitMessage{}
	for _, m := range messages {
		b = append(b, m)
	}
	return c.emitter.EmitBulk(ctx, b)
}

type DeviceIdCustomer_Synchronizer interface {
	Sync(DeviceIdCustomer_Synchronizer_Context) error
}

func Register_DeviceIdCustomer_Synchronizer(options runner.ServiceOptions, sychronizer DeviceIdCustomer_Synchronizer, updateInterval time.Duration) (func(context.Context) func() error, error) {
	brokers := options.Brokers
	protoWrapper := options.ProtoWrapper

	codec, err := protoWrapper.Codec("kafmesh.deviceId.customer", &deviceId.Customer{})
	if err != nil {
		return nil, errors.Wrap(err, "failed to create codec")
	}

	opts := &opt.Options{
		BlockCacheCapacity: opt.MiB * 1,
		WriteBuffer:        opt.MiB * 1,
	}

	path := filepath.Join("/tmp/storage", "synchronizer", "kafmesh.deviceId.customer")

	err = os.MkdirAll(path, os.ModePerm)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create synchronizer db directory")
	}

	builder := storage.BuilderWithOptions(path, opts)

	view, err := goka.NewView(brokers,
		goka.Table("kafmesh.deviceId.customer"),
		codec,
		goka.WithViewStorageBuilder(builder),
		goka.WithViewHasher(kafkautil.MurmurHasher),
	)

	if err != nil {
		return nil, errors.Wrap(err, "failed creating sychronizer view")
	}

	e, err := goka.NewEmitter(brokers,
		goka.Stream("kafmesh.deviceId.customer"),
		codec,
		goka.WithEmitterHasher(kafkautil.MurmurHasher))

	if err != nil {
		return nil, errors.Wrap(err, "failed creating sychronizer emitter")
	}

	emitter := runner.NewEmitter(e)

	c := &DeviceIdCustomer_Synchronizer_Context_impl{
		view:    view,
		emitter: emitter,
	}

	return func(ctx context.Context) func() error {
		return func() error {
			gctx, cancel := context.WithCancel(ctx)
			grp, gctx := errgroup.WithContext(ctx)

			timer := time.NewTimer(0)
			grp.Go(func() error {
				for {
					select {
					case <-gctx.Done():
						return nil
					case <-timer.C:
						err := sychronizer.Sync(c)
						if err != nil {
							return err
						}
						timer = time.NewTimer(updateInterval)
					}
				}
			})

			grp.Go(emitter.Watch(gctx))

			select {
			case <- ctx.Done():
				cancel()
				return nil
			case <- gctx.Done():
				cancel()
				err := grp.Wait()
				return err
			}
		}
	}, nil
}
