// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/syncromatics/kafmesh-example/internal/definitions/heartbeats/enriched_heartbeat_warehouse_sink_sink.km.go

// Package heartbeats is a generated GoMock package.
package heartbeats

import (
	gomock "github.com/golang/mock/gomock"
	runner "github.com/syncromatics/kafmesh/pkg/runner"
	deviceId "kafmesh-example/internal/definitions/models/kafmesh/deviceId"
	reflect "reflect"
)

// MockEnrichedHeartbeatWarehouseSink_Sink is a mock of EnrichedHeartbeatWarehouseSink_Sink interface
type MockEnrichedHeartbeatWarehouseSink_Sink struct {
	ctrl     *gomock.Controller
	recorder *MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder
}

// MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder is the mock recorder for MockEnrichedHeartbeatWarehouseSink_Sink
type MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder struct {
	mock *MockEnrichedHeartbeatWarehouseSink_Sink
}

// NewMockEnrichedHeartbeatWarehouseSink_Sink creates a new mock instance
func NewMockEnrichedHeartbeatWarehouseSink_Sink(ctrl *gomock.Controller) *MockEnrichedHeartbeatWarehouseSink_Sink {
	mock := &MockEnrichedHeartbeatWarehouseSink_Sink{ctrl: ctrl}
	mock.recorder = &MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEnrichedHeartbeatWarehouseSink_Sink) EXPECT() *MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder {
	return m.recorder
}

// Flush mocks base method
func (m *MockEnrichedHeartbeatWarehouseSink_Sink) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush
func (mr *MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockEnrichedHeartbeatWarehouseSink_Sink)(nil).Flush))
}

// Collect mocks base method
func (m *MockEnrichedHeartbeatWarehouseSink_Sink) Collect(ctx runner.MessageContext, key string, msg *deviceId.EnrichedHeartbeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, key, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect
func (mr *MockEnrichedHeartbeatWarehouseSink_SinkMockRecorder) Collect(ctx, key, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockEnrichedHeartbeatWarehouseSink_Sink)(nil).Collect), ctx, key, msg)
}
