// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/syncromatics/kafmesh-example/internal/definitions/details/deviceId_enrichedDetails_view.km.go

// Package details is a generated GoMock package.
package details

import (
	gomock "github.com/golang/mock/gomock"
	deviceId "kafmesh-example/internal/definitions/models/kafmesh/deviceId"
	reflect "reflect"
)

// MockDeviceIDEnrichedDetails_View is a mock of DeviceIDEnrichedDetails_View interface
type MockDeviceIDEnrichedDetails_View struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceIDEnrichedDetails_ViewMockRecorder
}

// MockDeviceIDEnrichedDetails_ViewMockRecorder is the mock recorder for MockDeviceIDEnrichedDetails_View
type MockDeviceIDEnrichedDetails_ViewMockRecorder struct {
	mock *MockDeviceIDEnrichedDetails_View
}

// NewMockDeviceIDEnrichedDetails_View creates a new mock instance
func NewMockDeviceIDEnrichedDetails_View(ctrl *gomock.Controller) *MockDeviceIDEnrichedDetails_View {
	mock := &MockDeviceIDEnrichedDetails_View{ctrl: ctrl}
	mock.recorder = &MockDeviceIDEnrichedDetails_ViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeviceIDEnrichedDetails_View) EXPECT() *MockDeviceIDEnrichedDetails_ViewMockRecorder {
	return m.recorder
}

// Keys mocks base method
func (m *MockDeviceIDEnrichedDetails_View) Keys() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Keys indicates an expected call of Keys
func (mr *MockDeviceIDEnrichedDetails_ViewMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockDeviceIDEnrichedDetails_View)(nil).Keys))
}

// Get mocks base method
func (m *MockDeviceIDEnrichedDetails_View) Get(key string) (*deviceId.EnrichedDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*deviceId.EnrichedDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockDeviceIDEnrichedDetails_ViewMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceIDEnrichedDetails_View)(nil).Get), key)
}
