// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jeff/source/kafmesh-example/internal/definitions/details/kafmesh_deviceId_enrichedDetails_view.km.go

// Package details is a generated GoMock package.
package details

import (
	gomock "github.com/golang/mock/gomock"
	deviceId "kafmesh-example/internal/definitions/models/kafmesh/deviceId"
	reflect "reflect"
)

// MockKafmeshDeviceIDEnrichedDetails_View is a mock of KafmeshDeviceIDEnrichedDetails_View interface
type MockKafmeshDeviceIDEnrichedDetails_View struct {
	ctrl     *gomock.Controller
	recorder *MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder
}

// MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder is the mock recorder for MockKafmeshDeviceIDEnrichedDetails_View
type MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder struct {
	mock *MockKafmeshDeviceIDEnrichedDetails_View
}

// NewMockKafmeshDeviceIDEnrichedDetails_View creates a new mock instance
func NewMockKafmeshDeviceIDEnrichedDetails_View(ctrl *gomock.Controller) *MockKafmeshDeviceIDEnrichedDetails_View {
	mock := &MockKafmeshDeviceIDEnrichedDetails_View{ctrl: ctrl}
	mock.recorder = &MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKafmeshDeviceIDEnrichedDetails_View) EXPECT() *MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder {
	return m.recorder
}

// Keys mocks base method
func (m *MockKafmeshDeviceIDEnrichedDetails_View) Keys() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Keys indicates an expected call of Keys
func (mr *MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockKafmeshDeviceIDEnrichedDetails_View)(nil).Keys))
}

// Get mocks base method
func (m *MockKafmeshDeviceIDEnrichedDetails_View) Get(key string) (*deviceId.EnrichedDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*deviceId.EnrichedDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockKafmeshDeviceIDEnrichedDetails_ViewMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKafmeshDeviceIDEnrichedDetails_View)(nil).Get), key)
}
