// Code generated by kafmesh-gen. DO NOT EDIT.

package details

import (
	"context"

	"github.com/burdiyan/kafkautil"
	"github.com/lovoo/goka"
	"github.com/pkg/errors"

	"github.com/syncromatics/kafmesh/pkg/runner"

	deviceId "kafmesh-example/internal/definitions/models/kafmesh/deviceId"
)

type DeviceIdDetails_Emitter interface {
	Emit(message DeviceIdDetails_Emitter_Message) error
	EmitBulk(ctx context.Context, messages []DeviceIdDetails_Emitter_Message) error
}

type DeviceIdDetails_Emitter_impl struct {
	emitter *runner.Emitter
}

type DeviceIdDetails_Emitter_Message struct {
	Key string
	Value *deviceId.Details
}

type impl_DeviceIdDetails_Emitter_Message struct {
	msg DeviceIdDetails_Emitter_Message
}

func (m *impl_DeviceIdDetails_Emitter_Message) Key() string {
	return m.msg.Key
}

func (m *impl_DeviceIdDetails_Emitter_Message) Value() interface{} {
	return m.msg.Value
}

func New_DeviceIdDetails_Emitter(options runner.ServiceOptions) (*DeviceIdDetails_Emitter_impl, error) {
	brokers := options.Brokers
	protoWrapper := options.ProtoWrapper

	codec, err := protoWrapper.Codec("kafmesh.deviceId.details", &deviceId.Details{})
	if err != nil {
		return nil, errors.Wrap(err, "failed to create codec")
	}

	emitter, err := goka.NewEmitter(brokers,
		goka.Stream("kafmesh.deviceId.details"),
		codec,
		goka.WithEmitterHasher(kafkautil.MurmurHasher))

	if err != nil {
		return nil, errors.Wrap(err, "failed creating emitter")
	}

	return &DeviceIdDetails_Emitter_impl{
		emitter: runner.NewEmitter(emitter),
	}, nil
}

func (e *DeviceIdDetails_Emitter_impl) Watch(ctx context.Context) func() error {
	return e.emitter.Watch(ctx)
}

func (e *DeviceIdDetails_Emitter_impl) Emit(message DeviceIdDetails_Emitter_Message) error {
	return e.emitter.Emit(message.Key, message.Value)
}

func (e *DeviceIdDetails_Emitter_impl) EmitBulk(ctx context.Context, messages []DeviceIdDetails_Emitter_Message) error {
	b := []runner.EmitMessage{}
	for _, m := range messages {
		b = append(b, &impl_DeviceIdDetails_Emitter_Message{msg: m})
	}
	return e.emitter.EmitBulk(ctx, b)
}
