// Code generated by kafmesh-gen. DO NOT EDIT.

package assignments

import (
	"context"

	"github.com/burdiyan/kafkautil"
	"github.com/lovoo/goka"
	"github.com/pkg/errors"

	"github.com/syncromatics/kafmesh/pkg/runner"

	deviceId "kafmesh-example/internal/kafmesh/definitions/models/kafmesh/deviceId"
)

type DeviceIdCustomer_Emitter interface {
	Emit(message *DeviceIdCustomer_Emitter_Message) error
	EmitBulk(ctx context.Context, messages []*DeviceIdCustomer_Emitter_Message) error
}

type DeviceIdCustomer_Emitter_impl struct {
	emitter *runner.Emitter
}

type DeviceIdCustomer_Emitter_Message struct {
	key string
	value *deviceId.Customer
}

func New_DeviceIdCustomer_Emitter_Message(key string, value *deviceId.Customer) *DeviceIdCustomer_Emitter_Message {
	return &DeviceIdCustomer_Emitter_Message{
		key: key,
		value: value,
	}
}

func (m *DeviceIdCustomer_Emitter_Message) Key() string {
	return m.key
}

func (m *DeviceIdCustomer_Emitter_Message) Value() interface{} {
	return m.value
}

func New_DeviceIdCustomer_Emitter(options runner.ServiceOptions) (*DeviceIdCustomer_Emitter_impl, error) {
	brokers := options.Brokers
	protoWrapper := options.ProtoWrapper

	codec, err := protoWrapper.Codec("kafmesh.deviceId.customer", &deviceId.Customer{})
	if err != nil {
		return nil, errors.Wrap(err, "failed to create codec")
	}

	emitter, err := goka.NewEmitter(brokers,
		goka.Stream("kafmesh.deviceId.customer"),
		codec,
		goka.WithEmitterHasher(kafkautil.MurmurHasher))

	if err != nil {
		return nil, errors.Wrap(err, "failed creating emitter")
	}

	return &DeviceIdCustomer_Emitter_impl{
		emitter: runner.NewEmitter(emitter),
	}, nil
}

func (e *DeviceIdCustomer_Emitter_impl) Watch(ctx context.Context) func() error {
	return e.emitter.Watch(ctx)
}

func (e *DeviceIdCustomer_Emitter_impl) Emit(message *DeviceIdCustomer_Emitter_Message) error {
	return e.emitter.Emit(message.Key(), message.Value())
}

func (e *DeviceIdCustomer_Emitter_impl) EmitBulk(ctx context.Context, messages []*DeviceIdCustomer_Emitter_Message) error {
	b := []runner.EmitMessage{}
	for _, m := range messages {
		b = append(b, m)
	}
	return e.emitter.EmitBulk(ctx, b)
}
